#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi


function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build Docker image.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        echo "Building building_detection Docker image"
        docker build -t building_detection -f Dockerfile .
    fi
fi
