#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Publishes building_detection image to ECR. Assumes that env var BUILDING_DETECTION_ECR_IMAGE is set to <ecr_repo_name>:<tag_name>.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
        exit
    fi

    AWS_REGION="ap-southeast-2"
    IMAGE_NAME="building_detection"
    PROFILE=${AWS_PROFILE}
    ACCOUNT_ID=$(aws sts get-caller-identity --profile ${PROFILE} --output text --query 'Account')

    aws ecr get-login --no-include-email --region ${AWS_REGION} --profile ${PROFILE} | bash;
    docker tag ${IMAGE_NAME} \
        ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$BUILDING_DETECTION_ECR_IMAGE
    docker push \
        ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$BUILDING_DETECTION_ECR_IMAGE
fi
